version: 2

jobs:
    # Build Cymetric
    build:
        docker:
            - image: cyclus/cycamore:latest
        working_directory: ~/cymetric
        steps:
            # Ensure your image has git (required by git to clone via SSH) so that CircleCI can clone your repo
            - run: apt-get -qq update; apt-get -y install git openssh-client
            - checkout
            - run:
                name: Build Cymetric
                command: |
                    python ./setup.py install --user
            - run:
                name: save SHA to a file
                command: echo $CIRCLE_SHA1 > .circle-sha
            - save_cache:
                key: v1-repo-{{ checksum ".circle-sha" }}
                paths:
                  - /root

    # Test
    nosetest:
        docker:
            - image: cyclus/cycamore:latest
        working_directory: ~/root
        steps:
            - run:
                name: save SHA to a file
                command: echo $CIRCLE_SHA1 > .circle-sha
            - restore_cache:
                keys:
                  - v1-repo-{{ checksum ".circle-sha" }}
            - run:
                name: Install nosetest
                command: pip install nose pyyaml
            - run:
                name: Nosetests
                command: nosetests -w ~/cymetric/tests; exit $?


    # Update docker container
    deploy: # Cymetric -> Cymetric:latest
        docker:
            - image: circleci/ruby:2.4-node
        working_directory: ~/cymetric
        steps:
            - checkout
            - run:
                name: Place the proper Dockerfile
                command: cp docker/master-ci/Dockerfile .
            - setup_remote_docker
            - run:
                name: log into Docker
                command: |
                    docker login -u $DOCKER_USER -p $DOCKER_PASS
            - run:
                name: Build Docker container
                command: docker build --rm=false -t cyclus/cymetric:latest .
            - run:
                name: Push on DockerHub
                command: docker push cyclus/cymetric:latest # push to docker depot

    deploy_stable: # Cymetric:stable
        docker:
            - image: circleci/ruby:2.4-node
        working_directory: ~/cymetric
        steps:
            - checkout
            - run:
                name: Place the proper Dockerfile
                command: cp docker/release-ci/Dockerfile .
            - setup_remote_docker
            - run:
                name: Log on DockerHub
                command: |
                  docker login -u $DOCKER_USER -p $DOCKER_PASS
            - run:
                name: Build Docker container
                command: docker build -t cyclus/cymetric:stable .
            - run:
                name: Push on DockerHub
                command: docker push cyclus/cymetric:stable # push to docker depot


workflows:
    version: 2
    build_and_test:
        jobs:

            # on a pr // all branch
            - build
            - nosetest:
                requires:
                    - build

            # Merge on Master
            - deploy:
                filters:
                    branches:
                        only: master
                requires:
                    - nosetest


             # The following should now be done on version tag.
            - deploy_stable:
                filters:
                    branches:
                        ignore: /.*/
                    tags:
                        only: /.*/
                requires:
                    - nosetest
