
FROM cyclus/cycamore:CYCAMORE_VERSION

RUN apt-get update
RUN apt-get install -y --force-yes --fix-missing python3-pip
RUN pip3 install cython numpy
RUN pip3 install tables
RUN pip3 install jinja2
RUN pip3 install pandas
RUN pip3 install numexpr argparse

