# set platform preprocessor macro
set(CYMETRIC_PLATFORM "__${CMAKE_SYSTEM_NAME}__")
if(APPLE)
    set(PYNE_PLATFORM "__APPLE__")
elseif(WIN32)
    if(MSVC)
        set(CYMETRIC_PLATFORM "__WIN_MSVC__")
    elseif(CMAKE_COMPILER_IS_GNUC OR CMAKE_COMPILER_IS_GNUCXX)
        set(CYMETRIC_PLATFORM "__WIN_GNUC__")
    endif(MSVC)
else(APPLE)
    set(CYMETRIC_PLATFORM "__LINUX__")
endif(APPLE)
set(CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} -D${CYMETRIC_PLATFORM}")
message("-- Cymetric platform defined as: ${CYMETRIC_PLATFORM}")

macro( print_logo )
  set(cat_prog cat)
  if(WIN32)
    set(cat_prog type)
  endif(WIN32)
  execute_process(COMMAND ${cat_prog} ${PROJECT_SOURCE_DIR}/cmake/logo.txt OUTPUT_VARIABLE variable)
  message("${variable}")
endmacro()
